## <strong>1. NumPy 배열</strong>

In [1]:
# Python 패키지 설치 명령어
!pip install numpy

In [2]:
# NumPy 불러오기
import numpy as np

### <strong>NumPy 배열 생성

In [3]:
# [+] 리스트 객체로부터 ndarray 객체 생성
my_lst = [1,2,3,4,5,6]
my_arr = np.array(my_lst)

my_arr

array([1, 2, 3, 4, 5, 6])

In [9]:
type([1,2,3])

list

# [+] 리스트/NumPy 배열 동시에 생성
np.array([1,2,3,4,5,])

#### **리스트 컴프리헨션 vs NumPy 배열**

In [10]:
# [+] 리스트 컴프리헨션을 이용하여 5달러씩 가격을 일괄적으로 할인하기
prices = [20, 40, 35, 10, 25, 56]
new_prices = [prices-5 for prices in prices]

new_prices

[15, 35, 30, 5, 20, 51]

In [12]:
# [+] NumPy 배열의 연산을 통한 5달러씩 가격을 일괄적으로 할인하기
prices_arr = np.array(prices)  # 배열 생성
prices_arr -= 5   # 가격 수정

prices_arr

array([15, 35, 30,  5, 20, 51])

#### **예제: 시험 점수 처리**

In [13]:
# 세 번의 시험에 대한 점수를 NumPy 배열로 선언
test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

In [18]:
# [+] 세 번째 시험에 2점씩 더하기
test_3_fixed = test_3 + 2 

test_3_fixed

array([89, 87, 74, 92, 94])

In [19]:
# [+] 학생 별 전체 시험 점수 총합 계산 
total_grade = test_1 + test_2 + test_3_fixed

total_grade

array([260, 281, 248, 276, 272])

In [20]:
# [+] 학생 별 평균 시험 점수 계산
final_grade = total_grade/3

final_grade

array([86.66666667, 93.66666667, 82.66666667, 92.        , 90.66666667])

In [21]:
# [+] 인덱싱: Jeremy의 두 번째 시험 점수
jeremy_test_2 = test_2[3]

jeremy_test_2

93

In [23]:
# [+] Manual과 Adwoa의 첫 번째 시험 점수
manual_adwoa_test_1 = test_1[1:3]

manual_adwoa_test_1

array([94, 88])

In [24]:
# [+] 전체 학생들의 점수를 2차원 배열에 저장
student_scores = np.array([test_1, test_2, test_3_fixed])

student_scores

array([[ 92,  94,  88,  91,  87],
       [ 79, 100,  86,  93,  91],
       [ 89,  87,  74,  92,  94]])

In [25]:
# [+] 2차원 배열 인덱싱: Tanya의 세 번째 시험 점수
student_scores[2,0]  

89

In [33]:
# [+] 2차원 배열 슬라이싱: Cody의 전체 시험 점수
#student_scores[0:3, 4:5]
student_scores[:3,4:5]  #같은 결과

array([[87],
       [91],
       [94]])

#### **배열 원소 단위의 논리 연산**

In [34]:
a = np.array([1, 20, 4, 6, 28, 88, 7, 12])

# [+] 10 이상 여부를 마스킹
mask = a > 5

mask

array([False,  True, False,  True,  True,  True,  True,  True])

In [35]:
# [+] 논리 연산을 이용하여 부분집합 구하기
selected = a[a>=10]

selected

array([20, 28, 88, 12])

In [36]:
# [+] 논리식 결합: 논리합
selected = a[(a>5)|(a<3)]

selected

array([ 1, 20,  6, 28, 88,  7, 12])

In [37]:
# [+] 논리식 결합: 논리곱
selected = a[(a>10)&(a<30)]

selected

array([20, 28, 12])

In [38]:
# [+] 정수 배열 생성, arange(stop)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
# [+] 정수 배열 생성, arange(start, stop)
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [41]:
# [+] 정수 배열 생성, arange(start, stop, interval)
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [51]:
# [+] 난수 배열 생성
np.random.seed(0)
arr = np.random.randint(10, size=(3,5))

arr

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1]])

### <strong>배열 조작 연산</strong>

In [52]:
# [+] 배열 속성
print(arr.ndim)     # 차원 수
print(arr.shape)    # 형상
print(arr.size)     # 크기
print(arr.dtype)    # 데이터 타입
print(arr.itemsize)  # 원소별 메모리 크기(bytes)
print(arr.nbytes)   # 전체 메모리 크기

2
(3, 5)
15
int32
4
60


In [53]:
# 배열 슬라이싱
arr = np.arange(10)
print(arr)

print(arr[3:7]) # 슬라이싱(start:stop)
print(arr[:5]) # 시작 인덱스 생략(:stop)
print(arr[5:]) # 종료 인덱스 생략(start:)
print(arr[::3]) # 간격(::interval)
print(arr[2:8:2]) # 슬라이싱(start:stop:interval)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6]
[0 1 2 3 4]
[5 6 7 8 9]
[0 3 6 9]
[2 4 6]


In [54]:
# 난수 배열 생성
np.random.seed(0) 
arr = np.random.randint(10, size=(6, 8)) 

arr

array([[5, 0, 3, 3, 7, 9, 3, 5],
       [2, 4, 7, 6, 8, 8, 1, 6],
       [7, 7, 8, 1, 5, 9, 8, 9],
       [4, 3, 0, 3, 5, 0, 2, 3],
       [8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7]])

In [55]:
# [+] 다차원 배열 슬라이싱
arr[3:5, 4:7]

array([[5, 0, 2],
       [3, 7, 0]])

In [56]:
# 배열 슬라이스 = 뷰(view)
arr_sub = arr[:2, :2]
print(arr_sub)

arr_sub[0, 0] = 99
print(arr_sub)

print(arr)

[[5 0]
 [2 4]]
[[99  0]
 [ 2  4]]
[[99  0  3  3  7  9  3  5]
 [ 2  4  7  6  8  8  1  6]
 [ 7  7  8  1  5  9  8  9]
 [ 4  3  0  3  5  0  2  3]
 [ 8  1  3  3  3  7  0  1]
 [ 9  9  0  4  7  3  2  7]]


In [59]:
# 배열 복사본 생성
arr_sub = arr[:2, :2].copy()

arr_sub[0, 0] = 50
print(arr_sub)

print(arr)

[[50  0]
 [ 2  4]]
[[99  0  3  3  7  9  3  5]
 [ 2  4  7  6  8  8  1  6]
 [ 7  7  8  1  5  9  8  9]
 [ 4  3  0  3  5  0  2  3]
 [ 8  1  3  3  3  7  0  1]
 [ 9  9  0  4  7  3  2  7]]


In [62]:
# [+] 배열 재구조화: reshape()
x = np.arange(10) # 0~9로 이루어진 배열 생성 (10,)
print(x)
print(x.shape)

x_reshaped = x.reshape(2,5) # 배열을 2X5 형상으로 재구조화
print(x_reshaped)
print(x_reshaped.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


In [63]:
# [+] 배열 재구조화: 차원 추가(np.newaxis)
arr = np.arange(3)
arr_new = arr[np.newaxis, :]
print(arr_new)
print(arr_new.shape)

[[0 1 2]]
(1, 3)


#### <strong> 배열 연결하기</strong>

In [64]:
# 세 개의 배열 생성
arr_1 = np.arange(1, 4)
arr_2 = np.arange(4, 7)
arr_3 = np.arange(7, 10)

print(arr_1, arr_2, arr_3)

[1 2 3] [4 5 6] [7 8 9]


In [65]:
# [+] 배열 연결: np.concatenate()
np.concatenate([arr_1, arr_2, arr_3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# [+] 배열 연결: 종연결 
np.vstack([arr_1, arr_2,arr_3])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
# 배열 연결: 횡연결
np.hstack([arr_1, arr_2, arr_3])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

# [+] 배열 분할 [1,2,3], [99,99], [3,2,1]
arr_1,arr_2,arry_3=np.split(arr,[3,5])
print(arr_1, arr_2, arr_3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99] [7 8 9]
